butler:
  importers:
    hypothesis:
      apikey: ""
      tagPrefix: "highlight/"
      category: "hypothesis"
      groups:
        - "my highlight library" 
  renderer:
    markdown:
      template: "./highlight_butler/resources/document.md"
      meta:
        tags: ["highlight"]
        category: "highlight"
  library:
    dir: "./pages/"
    filenamePrefix: "highlight_"